name: flutter_translator_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  translator: ^0.1.7
  google_fonts: ^2.3.1
  provider: ^6.0.2
  grouped_list: ^4.2.0
  intl: ^0.17.0
  flutter_screenutil: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
