name: g_translate_v2
description: "new flutter translate version"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  intl: ^0.19.0
  logger: ^2.3.0
  flutter_riverpod: ^2.5.1
  hive_local_storage: ^1.1.1
  flutter_screenutil: ^5.9.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.3
  hive_test: ^1.0.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  very_good_analysis: ^5.1.0
  envied_generator: ^0.5.4+1
  test_coverage_badge: ^0.2.0

flutter:
  uses-material-design: true
