name: flutter_translator_app
description: This app is a clone of google translate using their api keys
repository: https://github.com/camilo1498/flutter_translate_app
homepage: https://github.com/camilo1498
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  grouped_list: ^4.2.0
  intl: ^0.17.0
  flutter_screenutil: ^5.3.1
  flutter_keyboard_visibility: ^5.2.0
  dio: ^4.0.5
  sqflite: ^2.0.2
  fluttertoast: ^8.0.9
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
