class LanguagesList {
  static List<Map<String, String>> languageList = [
    {"code": "af-ZA", "name": "Afrikaans"},
    {"code": "sq", "name": "Albanian"},
    {"code": "ar-AE", "name": "Arabic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "bn-IN", "name": "Bengali"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "my", "name": "Burmese"},
    {"code": "ca-ES", "name": "Catalan"},
    {"code": "cmn-Hant-TW", "name": "Chinese"},
    {"code": "hr-HR", "name": "Croatian"},
    {"code": "cs-CZ", "name": "Czech"},
    {"code": "da-DK", "name": "Danish"},
    {"code": "nl-NL", "name": "Dutch"},
    {"code": "en-US", "name": "English"},
    {"code": "eo", "name": "Esperanto"},
    {"code": "et", "name": "Estonian"},
    {"code": "fil-PH", "name": "Filipino"},
    {"code": "fi-FI", "name": "Finnish"},
    {"code": "fr-FR", "name": "French"},
    {"code": "de-DE", "name": "German"},
    {"code": "el-GR", "name": "Greek"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "hi-IN", "name": "Hindi"},
    {"code": "hu-HU", "name": "Hungarian"},
    {"code": "is-IS", "name": "Icelandic"},
    {"code": "id-ID", "name": "Indonesian"},
    {"code": "it-IT", "name": "Italian"},
    {"code": "ja-JP", "name": "Japanese"},
    {"code": "kn", "name": "Kannada"},
    {"code": "km", "name": "Khmer"},
    {"code": "ko-KR", "name": "Korean"},
    {"code": "la", "name": "Latin"},
    {"code": "lv", "name": "Latvian"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mr", "name": "Marathi"},
    {"code": "ne", "name": "Nepali"},
    {"code": "no-NO", "name": "Norwegian"},
    {"code": "pl-PL", "name": "Polish"},
    {"code": "pt-BR", "name": "Portuguese"},
    {"code": "ro-RO", "name": "Romanian"},
    {"code": "ru-RU", "name": "Russian"},
    {"code": "sr-RS", "name": "Serbian"},
    {"code": "si", "name": "Sinhala"},
    {"code": "sk-SK", "name": "Slovak"},
    {"code": "es-MX", "name": "Spanish"},
    {"code": "sw", "name": "Swahili"},
    {"code": "sv-SE", "name": "Swedish"},
    {"code": "ta", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "th-TH", "name": "Thai"},
    {"code": "tr-TR", "name": "Turkish"},
    {"code": "uk-UA", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "vi-VN", "name": "Vietnamese"},
    {"code": "cy", "name": "Welsh"}
  ];

  /*final _langs = {
    'auto': 'Automatic',
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'am': 'Amharic',
    'ar': 'Arabic',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bn': 'Bengali',
    'bs': 'Bosnian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'ceb': 'Cebuano',
    'ny': 'Chichewa',
    'zh-cn': 'Chinese Simplified',
    'zh-tw': 'Chinese Traditional',
    'co': 'Corsican',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'en': 'English',
    'eo': 'Esperanto',
    'et': 'Estonian',
    'tl': 'Filipino',
    'fi': 'Finnish',
    'fr': 'French',
    'fy': 'Frisian',
    'gl': 'Galician',
    'ka': 'Georgian',
    'de': 'German',
    'el': 'Greek',
    'gu': 'Gujarati',
    'ht': 'Haitian Creole',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'iw': 'Hebrew',
    'hi': 'Hindi',
    'hmn': 'Hmong',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'ig': 'Igbo',
    'id': 'Indonesian',
    'ga': 'Irish',
    'it': 'Italian',
    'ja': 'Japanese',
    'jw': 'Javanese',
    'kn': 'Kannada',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'ko': 'Korean',
    'ku': 'Kurdish (Kurmanji)',
    'ky': 'Kyrgyz',
    'lo': 'Lao',
    'la': 'Latin',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'lb': 'Luxembourgish',
    'mk': 'Macedonian',
    'mg': 'Malagasy',
    'ms': 'Malay',
    'ml': 'Malayalam',
    'mt': 'Maltese',
    'mi': 'Maori',
    'mr': 'Marathi',
    'mn': 'Mongolian',
    'my': 'Myanmar (Burmese)',
    'ne': 'Nepali',
    'no': 'Norwegian',
    'ps': 'Pashto',
    'fa': 'Persian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'pa': 'Punjabi',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sm': 'Samoan',
    'gd': 'Scots Gaelic',
    'sr': 'Serbian',
    'st': 'Sesotho',
    'sn': 'Shona',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'es': 'Spanish',
    'su': 'Sundanese',
    'sw': 'Swahili',
    'sv': 'Swedish',
    'tg': 'Tajik',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'ug': 'Uyghur',
    'vi': 'Vietnamese',
    'cy': 'Welsh',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zu': 'Zulu'
  };*/
}
