import 'package:g_translate_v2/core/models/language_model.dart';

/// list of all google translate supported languages
class LanguagesList {
  static List<LanguageModel> languageList = _languageList
      .map(
        (item) => LanguageModel.fromJson(item),
      )
      .toList();

  static final List<Map<String, String>> _languageList = [
    {"code": "af", "name": "Afrikaans", "tts": "af-ZA"},
    {"code": "sq", "name": "Albanian", "tts": ""},
    {"code": "am", "name": "Amharic", "tts": ""},
    {"code": "ar", "name": "Arabic", "tts": "ar-AE"},
    {"code": "hy", "name": "Armenian", "tts": ""},
    {"code": "az", "name": "Azerbaijani", "tts": ""},
    {"code": "eu", "name": "Basque", "tts": ""},
    {"code": "be", "name": "Belarusian", "tts": ""},
    {"code": "bn", "name": "Bengali", "tts": "bn-IN"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "ca", "name": "Catalan", "tts": "ca-ES"},
    {"code": "ceb", "name": "Cebuano", "tts": ""},
    {"code": "ny", "name": "Chichewa", "tts": ""},
    {"code": "zh-CN", "name": "Chinese", "tts": "yue-HK"},
    {"code": "co", "name": "Corsican", "tts": ""},
    {"code": "hr", "name": "Croatian", "tts": ""},
    {"code": "cs", "name": "Czech", "tts": "cs-CZ"},
    {"code": "da", "name": "Danish", "tts": "da-DK"},
    {"code": "nl", "name": "Dutch", "tts": "nl-NL"},
    {"code": "en", "name": "English", "tts": "en-US"},
    {"code": "eo", "name": "Esperanto", "tts": ""},
    {"code": "et", "name": "Estonian", "tts": ""},
    {"code": "fil", "name": "Filipino", "tts": "fil-PH"},
    {"code": "fi", "name": "Finnish", "tts": "fi-FI"},
    {"code": "fr", "name": "French", "tts": "fr-FR"},
    {"code": "fy", "name": "Frisian", "tts": ""},
    {"code": "gl", "name": "Galician", "tts": ""},
    {"code": "ka", "name": "Georgian", "tts": ""},
    {"code": "de", "name": "German", "tts": "de-DE"},
    {"code": "el", "name": "Greek", "tts": "el-GR"},
    {"code": "gu", "name": "Gujarati", "tts": "gu-IN"},
    {"code": "ht", "name": "Haitian Creole", "tts": ""},
    {"code": "ha", "name": "Hausa", "tts": ""},
    {"code": "haw", "name": "Hawaiian", "tts": ""},
    {"code": "iw", "name": "Hebrew", "tts": ""},
    {"code": "hi", "name": "Hindi", "tts": "hi-IN"},
    {"code": "hmn", "name": "Hmong", "tts": ""},
    {"code": "hu", "name": "Hungarian", "tts": "hu-HU"},
    {"code": "is", "name": "Icelandic", "tts": "is-IS"},
    {"code": "ig", "name": "Igbo", "tts": ""},
    {"code": "id", "name": "Indonesian", "tts": "id-ID"},
    {"code": "ga", "name": "Irish", "tts": ""},
    {"code": "it", "name": "Italian", "tts": "it-IT"},
    {"code": "ja", "name": "Japanese", "tts": "ja-JP"},
    {"code": "jw", "name": "Javanese", "tts": ""},
    {"code": "kn", "name": "Kannada", "tts": "kn-IN"},
    {"code": "kk", "name": "Kazakh", "tts": ""},
    {"code": "km", "name": "Khmer", "tts": ""},
    {"code": "rw", "name": "kinyarwanda", "tts": ""},
    {"code": "ko", "name": "Korean", "tts": "ko-KR"},
    {"code": "ku", "name": "Kurdish", "tts": ""},
    {"code": "ky", "name": "Kyrgyz", "tts": ""},
    {"code": "lo", "name": "Lao", "tts": ""},
    {"code": "la", "name": "Latin", "tts": ""},
    {"code": "lv", "name": "Latvian", "tts": "lv-LV"},
    {"code": "lt", "name": "Lithuanian", "tts": ""},
    {"code": "lb", "name": "Luxembourgish", "tts": ""},
    {"code": "mk", "name": "Macedonian", "tts": ""},
    {"code": "mg", "name": "Malagasy", "tts": ""},
    {"code": "ms", "name": "Malay", "tts": "ms-MY"},
    {"code": "ml", "name": "Malayalam", "tts": "ml-IN"},
    {"code": "mt", "name": "Maltese", "tts": ""},
    {"code": "mi", "name": "Maori", "tts": ""},
    {"code": "mr", "name": "Marathi", "tts": ""},
    {"code": "mn", "name": "Mongolian", "tts": ""},
    {"code": "ne", "name": "Nepali", "tts": ""},
    {"code": "no", "name": "Norwegian", "tts": "no-NO"},
    {"code": "or", "name": "Odia", "tts": ""},
    {"code": "ps", "name": "Pashto", "tts": ""},
    {"code": "fa", "name": "Persian", "tts": ""},
    {"code": "pl", "name": "Polish", "tts": "pl-PL"},
    {"code": "pt", "name": "Portuguese", "tts": "pt-BR"},
    {"code": "pa", "name": "Punjabi", "tts": "pa-IN"},
    {"code": "ro", "name": "Romanian", "tts": "ro-RO"},
    {"code": "ru", "name": "Russian", "tts": "ru-RU"},
    {"code": "sm", "name": "Samoan", "tts": ""},
    {"code": "gd", "name": "Scots Gaelic", "tts": ""},
    {"code": "sr", "name": "Serbian", "tts": "sr-RS"},
    {"code": "st", "name": "Sesotho", "tts": ""},
    {"code": "sn", "name": "Shona", "tts": ""},
    {"code": "sd", "name": "Sindhi", "tts": ""},
    {"code": "si", "name": "Sinhala", "tts": ""},
    {"code": "sk", "name": "Slovak", "tts": "sk-SK"},
    {"code": "sl", "name": "Slovenian", "tts": ""},
    {"code": "so", "name": "Somali", "tts": ""},
    {"code": "es", "name": "Spanish", "tts": "es-MX"},
    {"code": "su", "name": "Sundanese", "tts": ""},
    {"code": "sw", "name": "Swahili", "tts": ""},
    {"code": "sv", "name": "Swedish", "tts": "sv-SE"},
    {"code": "tg", "name": "Tajik", "tts": ""},
    {"code": "ta", "name": "Tamil", "tts": "ta-IN"},
    {"code": "tt", "name": "Tatar", "tts": ""},
    {"code": "te", "name": "Telugu", "tts": "te-IN"},
    {"code": "th", "name": "Thai", "tts": "th-TH"},
    {"code": "tr", "name": "Turkish", "tts": "tr-TR"},
    {"code": "tk", "name": "Turkmen", "tts": ""},
    {"code": "uk", "name": "Ukrainian", "tts": "uk-UA"},
    {"code": "ur", "name": "Urdu", "tts": ""},
    {"code": "ug", "name": "Uyghur", "tts": ""},
    {"code": "uz", "name": "Uzbek", "tts": ""},
    {"code": "vi", "name": "Vietnamese", "tts": "vi-VN"},
    {"code": "cy", "name": "Welsh", "tts": ""},
    {"code": "xh", "name": "Xhosa", "tts": ""},
    {"code": "yi", "name": "Yiddish", "tts": ""},
    {"code": "yo", "name": "Yoruba", "tts": ""},
    {"code": "zu", "name": "Zulu", "tts": ""},
    {"code": "more-lang", "name": "More Languages"}
  ];
}
